### PR TITLE
Allow passing options to ring wrap-multipart-params.

### PR DESCRIPTION
**Pull request by ifesdjeen**
They're currently allowing :encoding and :store, 
which helps people (like me) who need to build custom
stores, such as EBS or others. 

This does not break any of the existing APIs.

A bit more details: Ring allows to override a store (default one is temp-file-store, which streams the input stream directly to the temporary file and gives you the path afterwards). 

Sometimes it's good to be able to store things in different ways, and have a better control over file upload while streaming the file.

### CODE REVIEW

**Comment by Raynes** [comment]
@ibdknox I'm not sure about this one. Could there be problems with options meaning different things to the different middleware that they get passed to?

**Comment by ibdknox** [comment]
it's reasonable to allow options there, but if we're going to do it, they should be keyed so that they don't conflict. e.g.

``` clojure
{:multipart-options {..}}
```

or something

**Comment by ifesdjeen** [comment]
Great. Thanks @ibdknox, will update PR shortly.

**Comment by Raynes** [comment]
@ifesdjeen Did you forget to update this pull request? If you do, I'll merge it.

**Comment by ifesdjeen** [comment]
Oh my, yes, I completely forgot about it. Could you leave it until the end of week, most likely I'll have to rewrite it according to the latest changes, a bit jammed with work ATM, but should handle within a week)

**Pull request closed without merging**
