### PR TITLE
Flashing added to session

### PR DESCRIPTION
**Pull request by jamiltron**
Since I wanted flashing to work in noir without any other dependencies I decided to just write it in, using noir-session, and using the swap-ingoing/outgoing idea used in sandbar.

I thought I'd issue a pull request because its working on my end, but I won't be offended if you wanted to do it a differen way.

Thank you,
Justin Hamilton

### CODE REVIEW

**Comment by ibdknox** [comment]
are you sure that works? The reason this has taken me a long time is because what happens if your page requests an image after it is loaded? That would constitute as the next request and clear out the flash, so it has to be intelligent about when it removes the flash. To fix that is a pretty invasive change to noir, so I'm trying to figure out the best way to do it.

**Comment by jamiltron** [comment]
Would an easy fix to that be keeping flashed messages in flash until they are retrieved? If I remember correctly that's kind of how they behaved in Rails. Although my understanding of how its handled in Ring is simply until the next request, no matter what that is.

**Comment by ibdknox** [comment]
That's definitely the simplest thing to do for now. I just committed and pushed to clojars. Let me know if that's fine for you :)

**Comment by jamiltron** [comment]
Thank you!

**Pull request closed without merging**
