### PR TITLE
BCrypt based crypt utilities

### PR DESCRIPTION
**Pull request by pyr**
Hi,

Great job on noir! I just made a simple change to replace the SHA based password encryption with BCrypt which provides much better security, since util/crypt is useful enough that it will probably get used widely it might be a good idea.

### CODE REVIEW

**Comment by ibdknox** [comment]
So much simpler than what I was doing too. I like offloading work on libraries that know what they're doing ;)

**Comment by alexandergitter** [comment]
The doc-string for encrypt still says "Uses SHA-256 encryption."

**Comment by ibdknox** [comment]
All fixed :)

**Comment by pyr** [comment]
oops, thanks ibdknox

**Pull request merged**
