### PR TITLE
Use BCrypt instead of SHA-256 as a password hashing algorithm

### PR DESCRIPTION
**Pull request by ghoseb**
Port the password hashing functions to use BCrypt instead of SHA-256 and fix function names, documentation.
- Add jBCrypt as a dependency
- Rename fn `encrypt` to `gen-hash` and fix it to use BCrypt
- Remove unnecessary fns & fix docs
- Fix tests
- Add swank-clojure as a dev dependency for poor Emacs users

### CODE REVIEW

**Comment by ghoseb** [comment]
I guess I got late by ~30 mins :)

**Comment by ghoseb** [comment]
Closing the request because it's not useful any more.

**Comment by ibdknox** [comment]
haha before I looked into it, I actually thought the other one was you. Kinda crazy that two people submitted basically the same patch within 30 minutes of eachother.

Thanks for the help ghoseb, it is greatly appreciated. :)

**Comment by ghoseb** [comment]
You are welcome. If you have a TODO list, put it on Github, I would like to contribute moar!

**Pull request closed without merging**
