### PR TITLE
Docstring fixes

### PR DESCRIPTION
**Pull request by kschuetz**
Hello.  
I've found a couple of typos in some of the docstrings in core.clj and fixed them.
Regards,
Kevin

### CODE REVIEW

**Comment by ibdknox** [comment]
can you make these against the 1.3 branch?

**Comment by kschuetz** [comment]
Sorry if that merge complicated things.  Let me know if you want me to submit a new pull request from scratch.

**Comment by Raynes** [comment]
If you still feel like it, could you toss another pull request in without the crazy merge stuff? This one can't be automatically merged and I don't have time to sort through it.

Thanks for the help and sorry nobody has responded to this in so long!

**Comment by kschuetz** [comment]
OK, I'll put in another pull request momentarily.

**Pull request closed without merging**
