### PR TITLE
Random custom middleware invocation order

### PR DESCRIPTION
**Pull request by mikeivanov**
A set-typed _middleware_ makes the order of custom middleware invocation unpredictable. This causes problems when one middleware sets data for another, like with authentication/authorization. The proposed change preserves the call order yet assures that custom middlewares are unique (although I don't think it is important).

### CODE REVIEW

**Comment by ibdknox** [comment]
Huh, I'm not sure why I originally did that as a set. It should definitely be a vector, though I'm not sure I understand why you changed it to a ref. I'll make this change in the vnext branch and push to Clojars. Noir 1.1.1-SNAPSHOT will have it.

**Comment by mikeivanov** [comment]
Hmm.. I might be wrong but a ref _feels_ more natural there. If you don't agree, here is an atom-based version:

```
(swap! *middleware* 
       (fn [mw] 
         (if (some #(= % mw)) 
           *middleware*
           (conj *middleware* mw)))
       [func args])
```

**Comment by abp** [comment]
Why does a ref feel more natural? It's a way to sync changes in transactions. Atoms are for independent changes. _middleware_ is independent here.

**Comment by mikeivanov** [comment]
You're right.

**Pull request closed without merging**
