### PR TITLE
Implemented functions to allow specify the redirect types (permanent, see other and temporary)

### PR DESCRIPTION
**Pull request by jonasfagundes**
permanent-redirect -> HTTP 301
see-other-redirect -> HTTP 303
temporary-redirect -> HTTP 307
redirect -> temporary-redirect

### CODE REVIEW

**Comment by Raynes** [comment]
@ibdknox This looks good. I definitely think we need this. When I moved refheap to heroku and started redirecting clients to www.refheap.com, all of the API clients failed and I couldn't figure out why they weren't following redirects. I'm pretty sure it's because noir's `redirect` is a temporary redirect rather than a permanent one. The documentation does not indicate this.

One thing I'm not sure about is the difference between `302` and `307`. This pull request modifies temporary redirect to be `307`, and I think that's the only thing you need to check out.

**Comment by Raynes** [comment]
Merged this, but changed the 307 to a 302.

**Comment by jonasfagundes** [comment]
@Raynes The 302 is old, in the HTTP 1.1 (from 1999, this is not recent) they changed it to 303 (See Other) and 307 (Temporary Redirect) to avoid ambiguity.

**Comment by ibdknox** [comment]
@jonas11235 several crawlers still use 1.0 randomly, so while 302 is old, it's a safer default choice.

**Comment by jonasfagundes** [comment]
@ibdknox, @Raynes I understand your concern with backward compatibility but I disagree with the approach. This way you are enforcing bad behavior  on applications that use noir (my application for example uses 307 with no problem). To have both, correct behavior and backward compatibility, we should have both methods available to allow developers to choose what fits better for their applications.

My suggestion:
temporary-redirect (307)
temporary-redirect-http10 (302)

If you accept my suggestion I can send a new patch.

**Comment by Raynes** [comment]
I strongly disagree that we should have two temporary redirect functions. These are very simple convenience functions that just keep you from having to type a ring response map. If you really, really need 307, you can always just write a map literal just like these functions do.

Also, a quick look at rails documentation tells me that they also default to 302 for the reasons that Chris detailed. However, it can also take a keyword indicating a type of redirect. I like this, so I'll propose another option.

@ibdknox I want to get rid of our individual redirect functions and add a new one that takes an optional second param that will be a keyword indicating what type of redirect to use. I can default to 302 which will keep `redirect` backwards compatible with existing code and I will document the status keywords well in the docstring. I think this is a good option.

``` clojure
(redirect "/hi" :temporary)
(redirect "/hi" :see-other)
(redirect "/hi" :permanent)
(redirect "/hi") ;; Just like the existing redirect, uses 302 'found'
...
```

What do you think, Chris? And would this be alright with you, @jonas11235?

**Comment by jonasfagundes** [comment]
@Raynes +1 to that, the interface is much simpler than what I had in mind, very nice solution it keeps backward compatibility and allows easy good behavior, really sweet!!

**Comment by Raynes** [comment]
@jonas11235 @ibdknox SHA: 074a10679a77a9c5d6a7123f3f3e401038676365

I've implemented this new redirect function on branch redirect. I'll merge it in as soon as Chris tells me he likes it. Don't want to be too aggressive in stealing his project. :p

**Comment by jonasfagundes** [comment]
@Raynes lol, don't worry about that, I'll distract him for you :P +1 for your patch

**Comment by ibdknox** [comment]
much better solution :) have at it!

**Comment by Raynes** [comment]
Done, and beta6 is released. Have at it!

**Pull request merged**
