### PR TITLE
Add support for `/:username'-style route

### PR DESCRIPTION
**Pull request by ghost**
To avoid route conflict with the catch-all route for static files, a
`:static-root` option is added to serve all static routes under one
common base root. So, to define a `/:username` route, you need to
- start server with a `:static-root` option, e.g.: `static`, so that
  all your static content live under `/static` URL path
- defpage a `/:username` route as normally

### CODE REVIEW

**Comment by ibdknox** [comment]
You can already do this simply by putting everything into a static folder under public:

resources/public/static/images
resources/public/static/css
...

Is there some aspect of this that I'm missing?

**Comment by ghost** [comment]
Hi Chris,

`/:username` is basically a `/*` route, and the catch-all resource route is a `/*` too, so the problem reduces to which `/*` should come first.

In the current code, if a username `/*` route is defined it will come before the resource `/*` route, so every resource request would go through the username handler which usually involves heavy-weight database operation to determine if the username exist. I think this is quite inefficient.

What my change does is putting all resource routes under one top-level path and make it come before the username `/*` route, this way we avoid the inefficiency.

Not sure if this justify the change. BTW thanks for this great stuff.

**Comment by ibdknox** [comment]
Ah I see. Actually, my solution still meets your needs because /:username works a bit differently than `/*`. `/:username` will only match a route with exactly one segment, while `/*` will match any route regardless of the number of segments. This means `/chris` will match, but `/chris/` will not. As a result, there can never be a conflict between `/:username` and `/static/images` for example.

Here's a simple test to prove what I said above:

``` clojure
(defpage "/:username" {:keys [username]} (str "hey " username))
(post-route "/*" [] (str "some resource might be here")
```

Then just try to access /chris and /static/images. It'll skip the username route, so you won't need to worry about taking the cost of hitting the db. :)

Cheers,
Chris.

**Comment by ghost** [comment]
Thanks for the detailed explanation, it makes sense and it works.

**Pull request closed without merging**
